# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Início
    url: /#top
    weight: 10
  - name: Sumário
    url: /#features
    weight: 20
  - name: Soluções
    url: /#solutions
    weight: 30
  - name: Recursos
    weight: 40
    hasChildren: true
  - parent: Recursos
    name: Blog
    url: blog/
